### PR TITLE
Added default setting for modern dock style in GWorkspace

### PR DESCRIPTION
**Pull request by KyleCardoza**

### CODE REVIEW

**Review by tedchoward — COMMENTED** [review]
I think this looks fine, but what does it do? I ran this on my machine, restarted GWorkspace, but I don't notice any changes. What should I be looking for?

**Comment by KyleCardoza** [comment]
It scans all installed applications to generate cached info that GWorkspace needs - it will become needed when the script installs more than just Terminal.

**Comment by tedchoward** [comment]
`defaults write GWorkspace dockstyle '<*I1>'` does a scan?

**Comment by KyleCardoza** [comment]
Oh, sorry I meant the make_services. The defaults thing makes the GWorkspace dock use the modern style, semitransparent background.

**Pull request merged**
